
import os
from pathlib import Path
from vector_embedded_finder import ingest_file, search, count

# Selected images from Downloads for testing
DOWNLOADS = Path("/Users/vedantbisen/Downloads")
TEST_FILES = [
    DOWNLOADS / "Porsche 911 Carrera GTS parked at side of road in village.jpg",
    DOWNLOADS / "GenED-logo-Colored.png",
    DOWNLOADS / "Gemini_Generated_Image_11tojk11tojk11to.png",
    DOWNLOADS / "Aarav.png",
]

def run_test():
    print("--- 🚀 VFinder Quick Test ---")
    
    # 1. Ingest files
    for file_path in TEST_FILES:
        if file_path.exists():
            print(f"Ingesting: {file_path.name}...")
            try:
                result = ingest_file(file_path)
                print(f"  Result: {result['status']}")
            except Exception as e:
                print(f"  Error ingesting {file_path.name}: {e}")
        else:
            print(f"File not found: {file_path}")

    print(f"\nTotal items in memory: {count()}")

    # 2. Perform searches
    queries = [
        "a luxury sports car",
        "a corporate logo",
        "a person's name",
        "something generated by AI"
    ]

    for q in queries:
        print(f"\n🔍 Searching for: '{q}'")
        results = search(q, n_results=2)
        if not results:
            print("  No matches found.")
            continue
            
        for i, r in enumerate(results, 1):
            score = f"{r['similarity'] * 100:.1f}%"
            print(f"  {i}. {r['file_name']} ({score} match)")

if __name__ == "__main__":
    run_test()
